# Generated by Django 5.2.1 on 2025-06-07 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_tag_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не меньше 1.')], verbose_name='Количество'),
        ),
    ]
